# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-02-28 09:40
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_only_read', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('level', models.IntegerField(choices=[(0, '\u4e00\u7ea7'), (1, '\u4e8c\u7ea7')])),
                ('type', models.IntegerField(choices=[(0, 'xxx'), (1, 'xxx'), (2, 'xxx')])),
                ('group', models.IntegerField()),
                ('parent', models.IntegerField()),
                ('identity', models.IntegerField(choices=[(0, '\u7cfb\u7edf\u7ba1\u7406'), (1, '\u5ba1\u8ba1\u7ba1\u7406'), (2, '\u5b89\u5168\u7ba1\u7406'), (3, '\u7cfb\u7edf\u4e1a\u52a1\u7ba1\u7406'), (4, '\u5ba1\u8ba1\u4e1a\u52a1\u7ba1\u7406')])),
            ],
            options={
                'db_table': 'v_module',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Module')),
            ],
            options={
                'db_table': 'v_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('identity', models.IntegerField(choices=[(0, '\u7cfb\u7edf\u7ba1\u7406'), (1, '\u5ba1\u8ba1\u7ba1\u7406'), (2, '\u5b89\u5168\u7ba1\u7406'), (3, '\u7cfb\u7edf\u4e1a\u52a1\u7ba1\u7406'), (4, '\u5ba1\u8ba1\u4e1a\u52a1\u7ba1\u7406')])),
            ],
            options={
                'db_table': 'v_role',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Role'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Role'),
        ),
    ]
