# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-02 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='codes',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
