# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-02 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='codes',
            field=models.CharField(default='', max_length=500),
        ),
    ]
