# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-02 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200302_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
