# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-02-28 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stat_time', models.DateTimeField(verbose_name=b'\xe6\x97\xb6\xe9\x97\xb4')),
                ('module', models.CharField(max_length=20, verbose_name=b'\xe5\x8a\x9f\xe8\x83\xbd\xe6\xa8\xa1\xe5\x9d\x97')),
                ('description', models.CharField(max_length=1000, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('source_ip', models.CharField(max_length=50, verbose_name=b'\xe5\xae\xa2\xe6\x88\xb7\xe7\xab\xafIP')),
                ('account_name', models.CharField(max_length=50, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('level0', models.IntegerField(choices=[(0, b'\xe6\xad\xa3\xe5\xb8\xb8'), (1, b'\xe5\xbc\x82\xe5\xb8\xb8')], default=0)),
            ],
            options={
                'db_table': 'v_auditrecord',
            },
        ),
    ]
