# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-02-28 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jijin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name=b'name')),
                ('code', models.CharField(max_length=20, verbose_name=b'code')),
                ('value', models.CharField(max_length=50, verbose_name=b'value')),
                ('timeStr', models.CharField(max_length=50, verbose_name=b'timeStr')),
            ],
            options={
                'db_table': 'v_jijin',
            },
        ),
    ]
