# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-03-03 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jijin',
            name='dqjz',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'value'),
        ),
        migrations.AddField(
            model_name='jijin',
            name='ztjz',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'value'),
        ),
        migrations.AddField(
            model_name='jijin',
            name='ztzf',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'value'),
        ),
    ]
