# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-05-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijin', '0002_auto_20200303_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='jijin',
            name='number',
            field=models.IntegerField(default=0, verbose_name=b'number'),
        ),
    ]
