# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-07-10 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijin', '0003_jijin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jijin',
            name='month',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'month'),
        ),
        migrations.AddField(
            model_name='jijin',
            name='month3',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'month3'),
        ),
        migrations.AddField(
            model_name='jijin',
            name='month6',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'month6'),
        ),
        migrations.AddField(
            model_name='jijin',
            name='overyear',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'overyear'),
        ),
        migrations.AddField(
            model_name='jijin',
            name='week',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'week'),
        ),
        migrations.AlterField(
            model_name='jijin',
            name='dqjz',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'dqjz'),
        ),
        migrations.AlterField(
            model_name='jijin',
            name='ztjz',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'ztjz'),
        ),
        migrations.AlterField(
            model_name='jijin',
            name='ztzf',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'ztzf'),
        ),
    ]
