# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2020-07-10 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jijin', '0004_auto_20200710_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='jijin',
            name='year',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'year'),
        ),
        migrations.AddField(
            model_name='jijin',
            name='year2',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'year2'),
        ),
        migrations.AddField(
            model_name='jijin',
            name='year3',
            field=models.CharField(default=b'', max_length=50, verbose_name=b'year3'),
        ),
    ]
